version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: blood_management_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blood_management
    ports:
      - "5432:5432"
    volumes:
      - blood_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  blood_pg_data:
